### ISSUE TITLE
Doesn't put "invalid" names in string

### ISSUE THREAD

**Issue by daveisfera** [villesau/optional-chaining-codemod#21]
Thanks for this awesome codemod!

While running on our code, we noticed that it doesn't handle names that need to be made strings correctly. For example, `get(['value', 'something-else'], data)` is changed to `data?.value?.something-else` when it should be `data?.value?.['something-else']`

**Comment by villesau** [comment]
Interesting! I think this issue is only with array representation of the path. with strings it already works:

https://github.com/villesau/optional-chaining-codemod/blob/master/__testfixtures__/transform.output.js#L18

https://github.com/villesau/optional-chaining-codemod/blob/master/__testfixtures__/transform.input.js#L21

Wanna submit a pull request? :) I'm fairly sure this is an easy fix.

**Comment by daveisfera** [comment]
Ya, I'll take a stab at it
